<?php

use Illuminate\Support\Facades\Route;
use Barryvdh\DomPDF\Facade\Pdf;

/**
 * TEMPORARY DIAGNOSTIC — not part of the app, delete this file (and
 * its require line in routes/web.php) once we've got an answer.
 *
 * Renders a PDF containing NOTHING but a single hardcoded 1x1 red
 * pixel PNG, embedded as a base64 data URI — no database, no file
 * storage, no QR library, no student data, nothing that could be
 * "your code's fault" in any way that isn't dompdf/PHP itself.
 *
 * Visit /diagnostic/dompdf-image in a browser (works on both local
 * and production — no auth needed) and open the PDF it downloads:
 *
 *   - See a small red square?  → dompdf CAN render embedded images in
 *     this environment. The problem is specific to how the real ID
 *     card template builds/passes its image data — tell me that, and
 *     I'll dig into the actual template logic instead of guessing at
 *     environment causes.
 *   - See a broken-image icon / "Image not found or type unknown" /
 *     blank space instead? → this environment's dompdf genuinely can't
 *     render ANY embedded image right now, confirming it's a
 *     GD/dompdf-config issue, not a bug in the ID card code. Send me
 *     that result and I'll go straight for the actual config problem
 *     instead of another round of template patches.
 *
 * Also visit /diagnostic/gd-check first — plain text output, no PDF
 * involved at all — to see directly whether GD is loaded in the exact
 * PHP process handling your web requests (not just CLI, which can
 * differ on XAMPP).
 */
Route::get('/diagnostic/gd-check', function () {
    return response()->json([
        'gd_extension_loaded' => extension_loaded('gd'),
        'gd_info' => extension_loaded('gd') ? gd_info() : null,
        'imagecreatefromstring_exists' => function_exists('imagecreatefromstring'),
        'php_sapi' => php_sapi_name(),
        'php_version' => PHP_VERSION,
    ]);
});

Route::get('/diagnostic/dompdf-image', function () {
    // A real 1x1 red pixel PNG, base64-encoded — not generated by any
    // of your code, just a known-good hardcoded constant.
    $redPixelPng = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=';

    $html = '<html><body style="margin:0;padding:40px;">
        <h3>Dompdf image diagnostic</h3>
        <p>If dompdf/GD is working in this environment, you should see a small red square below.</p>
        <img src="data:image/png;base64,'.$redPixelPng.'" style="width:100px;height:100px;border:1px solid #000;">
        <p style="margin-top:20px;">If you see a broken-image icon or nothing at all instead of a red square, that confirms this environment cannot render embedded images right now — regardless of anything in the ID card code.</p>
    </body></html>';

    return Pdf::loadHTML($html)->stream('dompdf-image-diagnostic.pdf');
});
