<?php

namespace App\Http\Controllers\Api\Media;

use App\Http\Controllers\Controller;
use App\Models\Payment;
use App\Models\Student;
use Illuminate\Support\Facades\Storage;

/**
 * Serves uploaded files through Laravel rather than exposing payment proofs
 * as permanent public /storage URLs.
 */
class MediaController extends Controller
{
    public function logo(string $path)
    {
        return $this->stream($path, 'school-logos/', 'public');
    }

    public function principalSignature(string $path)
    {
        return $this->stream($path, 'school-signatures/', 'public');
    }

    /**
     * Student photo access requires the signed URL generated by
     * Student::photo_url — see that accessor's docblock for why this
     * uses a 24-hour window rather than payment proofs' 30 minutes.
     * Same tenant check as everything else here happens implicitly:
     * the signature itself is only ever generated for the school that
     * legitimately owns this student, via serializing that Student
     * model — there's no separate school_id check needed on top.
     */
    public function studentPhoto(Student $student)
    {
        if (! request()->hasValidSignature()) {
            abort(403, 'This link has expired.');
        }

        if (! $student->photo_path) {
            abort(404);
        }

        return $this->stream($student->photo_path, 'student-photos/', 'private');
    }

    /**
     * Payment proof access requires the short-lived signed URL generated by
     * Payment::proof_url. New proofs live on the private disk. The public
     * fallback exists only for proofs uploaded by older versions of the app.
     */
    public function paymentProof(Payment $payment)
    {
        if (! request()->hasValidSignature()) {
            abort(403, 'This link has expired.');
        }

        if (! $payment->proof_path) {
            abort(404);
        }

        if (Storage::disk('private')->exists($payment->proof_path)) {
            return $this->stream($payment->proof_path, 'payment-proofs/', 'private');
        }

        // Legacy compatibility: old proofs were stored on the public disk.
        // New uploads never use this path.
        return $this->stream($payment->proof_path, 'payment-proofs/', 'public');
    }

    /**
     * Enrollment application payment proof — same signed-URL pattern
     * as paymentProof() above, generated by
     * EnrollmentApplicationController::show(). No legacy public-disk
     * fallback needed here since this is a new feature; every proof
     * under this path is already on the private disk.
     */
    public function enrollmentProof(\App\Models\EnrollmentApplication $enrollmentApplication)
    {
        if (! request()->hasValidSignature()) {
            abort(403, 'This link has expired.');
        }

        if (! $enrollmentApplication->payment_proof_path) {
            abort(404);
        }

        return $this->stream($enrollmentApplication->payment_proof_path, 'enrollment-proofs/', 'private');
    }

    private function stream(string $path, string $requiredPrefix, string $diskName)
    {
        $normalized = str_replace('\\', '/', $path);

        if (! str_starts_with($normalized, $requiredPrefix) || str_contains($normalized, '..')) {
            abort(404);
        }

        $disk = Storage::disk($diskName);

        if (! $disk->exists($normalized)) {
            abort(404);
        }

        return $disk->response($normalized);
    }
}
