<?php

namespace App\Http\Controllers\Api\Media;

use App\Http\Controllers\Controller;
use App\Models\Payment;
use Illuminate\Support\Facades\Storage;

/**
 * Serves uploaded files through Laravel rather than exposing payment proofs
 * as permanent public /storage URLs.
 */
class MediaController extends Controller
{
    public function logo(string $path)
    {
        return $this->stream($path, 'school-logos/', 'public');
    }

    /**
     * Payment proof access requires the short-lived signed URL generated by
     * Payment::proof_url. New proofs live on the private disk. The public
     * fallback exists only for proofs uploaded by older versions of the app.
     */
    public function paymentProof(Payment $payment)
    {
        if (! request()->hasValidSignature()) {
            abort(403, 'This link has expired.');
        }

        if (! $payment->proof_path) {
            abort(404);
        }

        if (Storage::disk('private')->exists($payment->proof_path)) {
            return $this->stream($payment->proof_path, 'payment-proofs/', 'private');
        }

        // Legacy compatibility: old proofs were stored on the public disk.
        // New uploads never use this path.
        return $this->stream($payment->proof_path, 'payment-proofs/', 'public');
    }

    private function stream(string $path, string $requiredPrefix, string $diskName)
    {
        $normalized = str_replace('\\', '/', $path);

        if (! str_starts_with($normalized, $requiredPrefix) || str_contains($normalized, '..')) {
            abort(404);
        }

        $disk = Storage::disk($diskName);

        if (! $disk->exists($normalized)) {
            abort(404);
        }

        return $disk->response($normalized);
    }
}
